pipeline:

  build-project:
    image: quay.io/ukhomeofficedigital/openjdk8:v1.1.0
    commands:
      - ./gradlew build
    when:
      event: [push, pull_request, tag]

  update-semver:
    image: quay.io/ukhomeofficedigital/docker-openjdk8-git:v1.5.0
    secrets:
      - github_ssh_key
    commands:
      - sh /root/git-utilities/set-up-github-user.sh "$${GITHUB_SSH_KEY}"
      - ./gradlew release -Prelease.useAutomaticVersion=true -x runBuildTasks -s -i
      - git describe --abbrev=0 --tags > ./tagSemver
    when:
      branch: [master]
      event: [push]

  docker-build:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t pttg-ip-hmrc .
    when:
      event: [push, tag]

  install-docker-image-with-githash-tag:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets:
      - docker_password
    commands:
      - docker login -u="ukhomeofficedigital+pttg" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag pttg-ip-hmrc quay.io/ukhomeofficedigital/pttg-ip-hmrc:${DRONE_COMMIT_SHA:0:8}
      - docker push quay.io/ukhomeofficedigital/pttg-ip-hmrc:${DRONE_COMMIT_SHA:0:8}
    when:
      event: push

  install-docker-image-from-feature-branch-build:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets:
      - docker_password
    commands:
      - docker login -u="ukhomeofficedigital+pttg" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag pttg-ip-hmrc quay.io/ukhomeofficedigital/pttg-ip-hmrc:${DRONE_BRANCH}
      - docker push quay.io/ukhomeofficedigital/pttg-ip-hmrc:${DRONE_BRANCH}
    when:
      branch:
        exclude: master
      event: push

  install-docker-image-from-master-branch-build:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets:
      - docker_password
    commands:
      - docker login -u="ukhomeofficedigital+pttg" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag pttg-ip-hmrc quay.io/ukhomeofficedigital/pttg-ip-hmrc:latest
      - docker push quay.io/ukhomeofficedigital/pttg-ip-hmrc:latest
      - docker tag pttg-ip-hmrc quay.io/ukhomeofficedigital/pttg-ip-hmrc:build-$${DRONE_BUILD_NUMBER}
      - docker push quay.io/ukhomeofficedigital/pttg-ip-hmrc:build-$${DRONE_BUILD_NUMBER}
      - docker tag pttg-ip-hmrc quay.io/ukhomeofficedigital/pttg-ip-hmrc:$(cat ./tagSemver)
      - docker push quay.io/ukhomeofficedigital/pttg-ip-hmrc:$(cat ./tagSemver)
    when:
      branch: master
      event: push

  tag-docker-image-with-git-tag:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets:
      - docker_password
    commands:
      - docker login -u="ukhomeofficedigital+pttg" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag pttg-ip-hmrc quay.io/ukhomeofficedigital/pttg-ip-hmrc:$${DRONE_TAG}
      - docker push quay.io/ukhomeofficedigital/pttg-ip-hmrc:$${DRONE_TAG}
      - docker tag pttg-ip-hmrc quay.io/ukhomeofficedigital/pttg-ip-hmrc:${DRONE_COMMIT_SHA:0:8}
      - docker push quay.io/ukhomeofficedigital/pttg-ip-hmrc:${DRONE_COMMIT_SHA:0:8}
      - docker tag pttg-ip-hmrc quay.io/ukhomeofficedigital/pttg-ip-hmrc:$(cat ./tagSemver)
      - docker push quay.io/ukhomeofficedigital/pttg-ip-hmrc:$(cat ./tagSemver)
    when:
      event: tag

  trigger-e2e-tests:
    image: quay.io/ukhomeofficedigital/drone-trigger:v0.3.0
    secrets:
      - DRONE_TOKEN
    drone_server: https://drone.acp.homeoffice.gov.uk
    repo: UKHomeOffice/pttg-ip-e2e-tests
    branch: master
    when:
      branch: [master]
      event: push

  clone-kube-project:
    image: plugins/git
    commands:
      - git clone https://github.com/UKHomeOffice/kube-pttg-ip-hmrc.git
    when:
      event: [push, tag, deployment]

  deploy-to-dev-from-build-number:
    image: quay.io/ukhomeofficedigital/kd:v1.14.0
    environment:
      - KUBE_NAMESPACE=pttg-ip-dev
      - ENVIRONMENT=dev
      - VERSION=build-${DRONE_BUILD_NUMBER}
      - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
    secrets:
      - pttg_ip_dev
    commands:
      - cd kube-pttg-ip-hmrc
      - ./deploy.sh
    when:
      branch: master
      event: [push, tag]

  deployment-to-not-prod:
    image: quay.io/ukhomeofficedigital/kd:v1.14.0
    environment:
      - KUBE_NAMESPACE=pttg-ip-${DRONE_DEPLOY_TO}
      - ENVIRONMENT=${DRONE_DEPLOY_TO}
      - VERSION=${IMAGE_VERSION}
      - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
    secrets:
      - pttg_ip_dev
    commands:
      - cd kube-pttg-ip-hmrc
      - ./deploy.sh
    when:
      event: deployment
      environment: [dev, test, feat1, feat2, feat3, preprod]

  deploy-to-prod:
    image: quay.io/ukhomeofficedigital/kd:v1.14.0
    environment:
      - KUBE_NAMESPACE=pttg-ip-${DRONE_DEPLOY_TO}
      - ENVIRONMENT=${DRONE_DEPLOY_TO}
      - VERSION=${IMAGE_VERSION}
      - KUBE_SERVER=https://kube-api-prod.prod.acp.homeoffice.gov.uk
    secrets:
      - pttg_ip_pr
    commands:
      - cd kube-pttg-ip-hmrc
      - ./deploy.sh
    when:
      event: deployment
      environment: pr
